var firstName=("Walter ");
var lastName=("Smith");
console.log(firstName);
console.log(lastName);
var fullname=firstName.concat(lastName);
console.log(fullname);
var number1=("10");
var number2=("5");
console.log(number1);
console.log(number2);
var number3 =(number1 + number2);
console.log(number3);